# Generated by Django 2.2.6 on 2020-01-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tickets',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(max_length=250),
        ),
    ]
